
services:
    php:
      build:
        context: .
        dockerfile: ./images/phpfpm/Dockerfile
      volumes:
        - './src:/var/www/html'
      depends_on:
        - db

    nginx:
        image: nginx:latest
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - './src:/var/www/html'
            - './images/nginx:/etc/nginx/conf.d'
        depends_on:
          - php

    db:
      image: mysql:latest
      ports:
          - "3306:3306"
      environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: database
          MYSQL_USER: user
          MYSQL_PASSWORD: password
      volumes:
          - dbdata:/var/lib/mysql

    phpmyadmin:
      image: phpmyadmin/phpmyadmin:latest
      environment:
          PMA_HOST: db
          PMA_USER: user
          PMA_PASSWORD: password
      ports:
      - 8081:80

volumes:
  dbdata:
